name: Snapshot

on:
  push:
    branches:
      - master

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven and set up Apache Maven Central
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-password: GH_TOKEN

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Determine current version
        id: release_version
        run: echo ::set-output name=release_version::`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`

      - name: Deploy site
        if: ${{ endsWith(steps.release_version.outputs.release_version, 'SNAPSHOT') }}
        run: mvn site -Dsite.path=snapshot
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Deploy snapshot
        if: ${{ endsWith(steps.release_version.outputs.release_version, 'SNAPSHOT') }}
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.GPG_FILE }}
          gpg_passphrase: ${{ secrets.GPG_PASSWORD }}
          nexus_username: ${{ secrets.SONATYPE_USERNAME }}
          nexus_password: ${{ secrets.SONATYPE_PASSWORD }}
