name: Windows CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  snapshot:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven and set up Apache Maven Central
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-password: GH_TOKEN

      - name: Cache Maven packages
        uses: actions/cache@v2.1.4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests
        run: mvn verify -Prun-its


